services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: pnpm start:dev user
    depends_on:
      postgres_user:
        condition: service_healthy
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./apps/user/.env

  postgres_user:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker-volumes/postgres/user:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
