apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: {{ .Chart.Name }}-payment-cluster-ip

spec:
  ports:
    - port: 3013
      protocol: TCP
      targetPort: 3013
  selector:
    app: payment
  type: ClusterIP
    
