apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config-map
data:
  PORT: "3004"
  GRPC_PAYMENT_URL: "0.0.0.0:3013"
  GRPC_NOTIFICATION_URL: "{{.Chart.Name}}-notification-cluster-ip:3015"
  TCP_PORT: "3000"
  NOTIFICATION_HOST: notification
  NOTIFICATION_TCP_PORT: "3000"
