apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-payment-deployment
  labels:
    app: payment

spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: payment
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: karlcoco/fc-nestjs-payment:latest
          envFrom:
            - configMapRef:
                name: payment-config-map
            - secretRef:
                name: payment-secret
          ports:
            - containerPort: 3013
          livenessProbe:
            tcpSocket:
              port: 3013
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3013
            periodSeconds: 5
    
