apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: {{ .Chart.Name }}-notification-cluster-ip

spec:
  ports:
    - port: 3015
      protocol: TCP
      targetPort: 3015
  selector:
    app: notification
  type: ClusterIP
    
