apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: {{ .Chart.Name }}-order-cluster-ip

spec:
  ports:
    - port: 3014
      protocol: TCP
      targetPort: 3014
  selector:
    app: order
  type: ClusterIP
    
