apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: {{ .Chart.Name }}-user-cluster-ip

spec:
  ports:
    - port: 3011
      protocol: TCP
      targetPort: 3011
  selector:
    app: user
  type: ClusterIP
    
